/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaboratoryIndexRouteImport } from './routes/laboratory/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as LaboratoryProjectSlugRouteRouteImport } from './routes/laboratory/$projectSlug/route'
import { Route as EventsEventSlugRouteRouteImport } from './routes/events/$eventSlug/route'
import { Route as LaboratoryProjectSlugIndexRouteImport } from './routes/laboratory/$projectSlug/index'
import { Route as EventsEventSlugIndexRouteImport } from './routes/events/$eventSlug/index'
import { Route as EventsEventSlugGalleryRouteImport } from './routes/events/$eventSlug/gallery'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryIndexRoute = LaboratoryIndexRouteImport.update({
  id: '/laboratory/',
  path: '/laboratory/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryProjectSlugRouteRoute =
  LaboratoryProjectSlugRouteRouteImport.update({
    id: '/laboratory/$projectSlug',
    path: '/laboratory/$projectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventSlugRouteRoute = EventsEventSlugRouteRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryProjectSlugIndexRoute =
  LaboratoryProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LaboratoryProjectSlugRouteRoute,
  } as any)
const EventsEventSlugIndexRoute = EventsEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)
const EventsEventSlugGalleryRoute = EventsEventSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/laboratory/$projectSlug': typeof LaboratoryProjectSlugRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/laboratory/': typeof LaboratoryIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
  '/laboratory/$projectSlug/': typeof LaboratoryProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsIndexRoute
  '/laboratory': typeof LaboratoryIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug': typeof EventsEventSlugIndexRoute
  '/laboratory/$projectSlug': typeof LaboratoryProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/laboratory/$projectSlug': typeof LaboratoryProjectSlugRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/laboratory/': typeof LaboratoryIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
  '/laboratory/$projectSlug/': typeof LaboratoryProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events/$eventSlug'
    | '/laboratory/$projectSlug'
    | '/events/'
    | '/laboratory/'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug/'
    | '/laboratory/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/laboratory'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug'
    | '/laboratory/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events/$eventSlug'
    | '/laboratory/$projectSlug'
    | '/events/'
    | '/laboratory/'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug/'
    | '/laboratory/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsEventSlugRouteRoute: typeof EventsEventSlugRouteRouteWithChildren
  LaboratoryProjectSlugRouteRoute: typeof LaboratoryProjectSlugRouteRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
  LaboratoryIndexRoute: typeof LaboratoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory/': {
      id: '/laboratory/'
      path: '/laboratory'
      fullPath: '/laboratory/'
      preLoaderRoute: typeof LaboratoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory/$projectSlug': {
      id: '/laboratory/$projectSlug'
      path: '/laboratory/$projectSlug'
      fullPath: '/laboratory/$projectSlug'
      preLoaderRoute: typeof LaboratoryProjectSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory/$projectSlug/': {
      id: '/laboratory/$projectSlug/'
      path: '/'
      fullPath: '/laboratory/$projectSlug/'
      preLoaderRoute: typeof LaboratoryProjectSlugIndexRouteImport
      parentRoute: typeof LaboratoryProjectSlugRouteRoute
    }
    '/events/$eventSlug/': {
      id: '/events/$eventSlug/'
      path: '/'
      fullPath: '/events/$eventSlug/'
      preLoaderRoute: typeof EventsEventSlugIndexRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
    '/events/$eventSlug/gallery': {
      id: '/events/$eventSlug/gallery'
      path: '/gallery'
      fullPath: '/events/$eventSlug/gallery'
      preLoaderRoute: typeof EventsEventSlugGalleryRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
  }
}

interface EventsEventSlugRouteRouteChildren {
  EventsEventSlugGalleryRoute: typeof EventsEventSlugGalleryRoute
  EventsEventSlugIndexRoute: typeof EventsEventSlugIndexRoute
}

const EventsEventSlugRouteRouteChildren: EventsEventSlugRouteRouteChildren = {
  EventsEventSlugGalleryRoute: EventsEventSlugGalleryRoute,
  EventsEventSlugIndexRoute: EventsEventSlugIndexRoute,
}

const EventsEventSlugRouteRouteWithChildren =
  EventsEventSlugRouteRoute._addFileChildren(EventsEventSlugRouteRouteChildren)

interface LaboratoryProjectSlugRouteRouteChildren {
  LaboratoryProjectSlugIndexRoute: typeof LaboratoryProjectSlugIndexRoute
}

const LaboratoryProjectSlugRouteRouteChildren: LaboratoryProjectSlugRouteRouteChildren =
  {
    LaboratoryProjectSlugIndexRoute: LaboratoryProjectSlugIndexRoute,
  }

const LaboratoryProjectSlugRouteRouteWithChildren =
  LaboratoryProjectSlugRouteRoute._addFileChildren(
    LaboratoryProjectSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsEventSlugRouteRoute: EventsEventSlugRouteRouteWithChildren,
  LaboratoryProjectSlugRouteRoute: LaboratoryProjectSlugRouteRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
  LaboratoryIndexRoute: LaboratoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
