/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRequestRouteImport } from './routes/quote-request'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventSlugRouteRouteImport } from './routes/events/$eventSlug/route'
import { Route as EventsEventSlugIndexRouteImport } from './routes/events/$eventSlug/index'
import { Route as EventsEventSlugGalleryRouteImport } from './routes/events/$eventSlug/gallery'

const QuoteRequestRoute = QuoteRequestRouteImport.update({
  id: '/quote-request',
  path: '/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventSlugRouteRoute = EventsEventSlugRouteRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventSlugIndexRoute = EventsEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)
const EventsEventSlugGalleryRoute = EventsEventSlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote-request': typeof QuoteRequestRoute
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote-request': typeof QuoteRequestRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug': typeof EventsEventSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quote-request': typeof QuoteRequestRoute
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/events/$eventSlug/gallery': typeof EventsEventSlugGalleryRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/quote-request'
    | '/events/$eventSlug'
    | '/events/'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/quote-request'
    | '/events'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/quote-request'
    | '/events/$eventSlug'
    | '/events/'
    | '/events/$eventSlug/gallery'
    | '/events/$eventSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  QuoteRequestRoute: typeof QuoteRequestRoute
  EventsEventSlugRouteRoute: typeof EventsEventSlugRouteRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote-request': {
      id: '/quote-request'
      path: '/quote-request'
      fullPath: '/quote-request'
      preLoaderRoute: typeof QuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlug/': {
      id: '/events/$eventSlug/'
      path: '/'
      fullPath: '/events/$eventSlug/'
      preLoaderRoute: typeof EventsEventSlugIndexRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
    '/events/$eventSlug/gallery': {
      id: '/events/$eventSlug/gallery'
      path: '/gallery'
      fullPath: '/events/$eventSlug/gallery'
      preLoaderRoute: typeof EventsEventSlugGalleryRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
  }
}

interface EventsEventSlugRouteRouteChildren {
  EventsEventSlugGalleryRoute: typeof EventsEventSlugGalleryRoute
  EventsEventSlugIndexRoute: typeof EventsEventSlugIndexRoute
}

const EventsEventSlugRouteRouteChildren: EventsEventSlugRouteRouteChildren = {
  EventsEventSlugGalleryRoute: EventsEventSlugGalleryRoute,
  EventsEventSlugIndexRoute: EventsEventSlugIndexRoute,
}

const EventsEventSlugRouteRouteWithChildren =
  EventsEventSlugRouteRoute._addFileChildren(EventsEventSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  QuoteRequestRoute: QuoteRequestRoute,
  EventsEventSlugRouteRoute: EventsEventSlugRouteRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
